# [build]
# builder = "dockerfile"

# [deploy]
# healthcheckPath = "/health"
# healthcheckTimeout = 100
# restartPolicyType = "on_failure"
# restartPolicyMaxRetries = 10

# [env]
# PORT = "8000"


[deploy]
startCommand = "python main.py"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"

[build]
builder = "NIXPACKS"
