# [build]
# builder = "dockerfile"

# [deploy]
# healthcheckPath = "/health"
# healthcheckTimeout = 100
# restartPolicyType = "on_failure"
# restartPolicyMaxRetries = 10

# [env]
# PORT = "8000"


[deploy]
startCommand = "uvicorn app.main:app --host 0.0.0.0 --port ${PORT:-8000}"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"

[build]
builder = "NIXPACKS"
